version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: cryptocurrency-trading-platform-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cryptocurrency-trading-platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: